//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGUI {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class UserOptions : global::System.Configuration.ApplicationSettingsBase {
        
        private static UserOptions defaultInstance = ((UserOptions)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UserOptions())));
        
        public static UserOptions Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Not Set")]
        public string ExEdS {
            get {
                return ((string)(this["ExEdS"]));
            }
            set {
                this["ExEdS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Not Set")]
        public string TermS {
            get {
                return ((string)(this["TermS"]));
            }
            set {
                this["TermS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Not Set")]
        public string Usr2S {
            get {
                return ((string)(this["Usr2S"]));
            }
            set {
                this["Usr2S"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Not Set")]
        public string Usr3S {
            get {
                return ((string)(this["Usr3S"]));
            }
            set {
                this["Usr3S"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tools")]
        public string BtnExEdS {
            get {
                return ((string)(this["BtnExEdS"]));
            }
            set {
                this["BtnExEdS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tools")]
        public string BtnTermS {
            get {
                return ((string)(this["BtnTermS"]));
            }
            set {
                this["BtnTermS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tools")]
        public string BtnUsr2S {
            get {
                return ((string)(this["BtnUsr2S"]));
            }
            set {
                this["BtnUsr2S"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tools")]
        public string BtnUsr3S {
            get {
                return ((string)(this["BtnUsr3S"]));
            }
            set {
                this["BtnUsr3S"] = value;
            }
        }
    }
}
